spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 
    lettuce:      pool:        max-active: 200
        max-wait: 10
        min-idle: 0
    timeout: 1000
      